name: CI
on:
  push:
    branches: [ master ]
    tags:
      - v*.*
jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: setup jdk
        uses: actions/setup-java@v2
        with: 
          distribution: 'adopt'
          java-version: '11'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: compile java source code
        run: ./gradlew compileJava
  test:
    needs: compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2    
          
      - name: setup jdk
        uses: actions/setup-java@v2
        with: 
          distribution: 'adopt'
          java-version: '11'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: test
        run: ./gradlew test

      - name: upload test report
        uses: actions/upload-artifact@v2
        with: 
          name: test_report
          path: ./build/reports/tests/test

  assemble:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      jar_file_name: ${{ steps.save_file_name.outputs.jar_file_name }}
    steps:
      - uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v2
        with: 
          distribution: 'adopt'
          java-version: '11'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: assemble
        run: ./gradlew assemble

      - name: setup env
        run: echo "jar_file_name=`ls ./build/libs/`" >> $GITHUB_ENV

      - id: save_file_name
        run: echo "::set-output name=jar_file_name::${{env.jar_file_name}}"

      - name: upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: jar file
          path: ./build/libs

  release:
    if: ${{ startsWith(github.ref,'refs/tags/') }}
    needs: assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
       
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: jar file
          path: ./download/artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./download/artifacts/${{needs.assemble.outputs.jar_file_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
