# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup jdk
        uses: actions/setup-java@v2
        with: 
          distribution: 'adopt'
          java-version: '11'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: compile java source code
        run: ./gradlew compileJava
  test:
    needs: compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2    
          
      - name: setup jdk
        uses: actions/setup-java@v2
        with: 
          distribution: 'adopt'
          java-version: '11'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: test
        run: ./gradlew test

      - name: upload test report
        uses: actions/upload-artifact@v2
        with: 
          name: test_report
          path: ./build/reports/tests/test

  assemble:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v2
        with: 
          distribution: 'adopt'
          java-version: '11'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: assemble
        run: ./gradlew assemble

